name: Build & Publish Flatpak to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Flatpak tools
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Setup Freedesktop (if needed)
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak update -y
          sudo flatpak install -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08

      - name: Build Flatpak OSTree Repo
        run: |
          # Build your Flatpak into a local repo/ folder
          flatpak-builder --force-clean --repo=repo build-dir com.asimov_platform.asimov_cli.yaml
          # Update the summary so Flatpak can read it
          ostree --repo=repo summary -u

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Deploy the 'repo' folder to gh-pages branch
          publish_dir: repo
          publish_branch: gh-pages
