name: Test Flatpak

on: [push]

jobs:
  build-and-test-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Setup Flatpak environment
        run: |
          # Add the Flathub remote so we can pull down the Freedesktop Platform & SDK
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

          # Update to fetch remote info
          sudo flatpak update -y

          # Install the 23.08 runtime and SDK needed by your manifest
          sudo flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      - name: Build the Flatpak
        run: |
          flatpak-builder --force-clean build-dir com.asimov_platform.asimov_cli.yaml

      - name: Install and Test the CLI
        run: |
          flatpak-builder --user --install --force-clean build-dir com.asimov_platform.asimov_cli.yaml
          flatpak run com.asimov_platform.asimov_cli sh -c 'asimov --version'
